"""Generate docs/formats.md from the backend registry and profile definitions.  Run: python scripts/gen_profiles_doc.py"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from edb_explorer.core.backends import KINDS
from edb_explorer.core.profiles import all_profiles
from edb_explorer.core.values import TIMESTAMP_KINDS

PLATFORM_NAMES = {
    "windows": "Windows",
    "macos": "macOS",
    "ios": "iOS",
    "android": "Android",
    "linux": "Linux",
    "browser": "Browsers",
    "server": "Servers",
    "cross": "Cross-platform",
    "": "Other",
}


def main() -> None:
    out = [
        "# Supported formats and application profiles",
        "",
        "*Generated by `scripts/gen_profiles_doc.py` - do not edit by hand.*",
        "",
        "## File formats",
        "",
        "| Kind | Name | Typical files | Extensions |",
        "|---|---|---|---|",
    ]
    for k in KINDS:
        out.append(f"| `{k.id}` | {k.name} | {k.description} | {' '.join(f'`{e}`' for e in k.extensions)} |")
    out += [
        "",
        "Files are recognised by signature, not extension. A LevelDB store is a *directory*; opening any file",
        "inside it (`CURRENT`, `*.ldb`, `*.log`) opens the whole store.",
        "",
        "## Application profiles",
        "",
        "A profile is matched from the table names (and file name) of an opened database. It supplies friendly table",
        "names, the timestamp encoding of known columns and ready-made **artifact views** (SQL) that appear under",
        "*Analysis views* in the GUI, `edb-explorer views`, and the `list_views` / `run_view` MCP tools.",
        "",
    ]
    groups: dict[str, list] = {}
    for p in all_profiles():
        groups.setdefault(p.platform or "", []).append(p)
    for plat in ("windows", "macos", "ios", "android", "browser", "linux", "server", "cross", ""):
        if plat not in groups:
            continue
        out += [f"### {PLATFORM_NAMES[plat]}", "", "| Profile | Formats | Identified by | Views |", "|---|---|---|---|"]
        for p in groups[plat]:
            sig = ", ".join(f"`{t}`" for t in p.signature_tables) or "(format only)"
            views = ", ".join(f"`{v.id}`" for v in p.views) or "-"
            fmts = ", ".join(p.kinds) or "any"
            out.append(f"| **{p.name}**<br>{p.description} | {fmts} | {sig} | {views} |")
        out.append("")
    out += ["## Timestamp encodings", "", "| Kind | Meaning |", "|---|---|"]
    for k, v in TIMESTAMP_KINDS.items():
        out.append(f"| `{k}` | {v} |")
    out += [
        "",
        "Columns not covered by a profile are still detected heuristically (`detect_timestamps`, column statistics,",
        "timeline) from their value ranges and names.",
        "",
    ]
    target = Path(__file__).resolve().parents[1] / "docs" / "formats.md"
    target.write_text("\n".join(out), encoding="utf-8")
    print(f"wrote {target} ({len(all_profiles())} profiles)")


if __name__ == "__main__":
    main()
